---
title: "Web Scrape"
output: html_notebook
---


```{r, results='hide', message=FALSE}
include <- function(library_name){
  if(!(library_name %in% installed.packages()))
    install.packages(library_name)
  library(library_name, character.only=TRUE)
}
include("rvest")
include("tidyr")
include("dplyr")
```


```{r}
read_class_schedule <- function(url) {
  schedule_html <- read_html(url)
  
  title <- schedule_html %>% html_node(".subjpagessubjheader")
              %>% html_text()
  
  classes <- schedule_html %>% html_nodes(".classrow")

  class_title <- classes %>%
                html_nodes("td.title") %>%
                html_text()
  class_subject <- classes %>%
                html_nodes("td.subj") %>%
                html_text()
  class_number <- classes %>%
                html_nodes("td.cat_num") %>%
                html_text()
  section_number <- classes %>%
                html_nodes("td.sect") %>%
                html_text()
  instructor <- classes %>%
                html_nodes("td.Instructor") %>%
                html_text()
  enrollment <- classes %>%
                html_nodes("td.enrtot") %>%
                html_text()

  tibble(class_title, class_subject, class_number,section_number, instructor, enrollment)
  
}

url <- "http://ems.csuchico.edu/APSS/schedule/spr2019/CSCI.shtml"
CSCI_spring_2019 <- read_class_schedule(url)
url <- "http://ems.csuchico.edu/APSS/schedule/spr2020/CSCI.shtml"
CSCI_spring_2020 <- read_class_schedule(url)
url <- "http://ems.csuchico.edu/APSS/schedule/spr2019/MATH.shtml"
MATH_spring_2019 <- read_class_schedule(url)
url <- "http://ems.csuchico.edu/APSS/schedule/spr2020/MATH.shtml"
MATH_spring_2020 <- read_class_schedule(url)


all_classes <- bind_rows(CSCI_spring_2019, CSCI_spring_2020, MATH_spring_2019, MATH_spring_2020)
```


